name: flutter_is_emulator_fixed
description: Plugin to detect whether the current device is an emulator or simulator (forked and fixed)
version: 1.0.0
author: Edouard Marquez <moi@edouard-marquez.me>
homepage: https://github.com/dave/flutter_is_emulator_fixed

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: fr.g123k.flutterisemulator
        pluginClass: FlutterIsEmulatorPlugin

environment:
  sdk: ">=1.19.0 <3.0.0"
  flutter: ">=0.1.2 <2.0.0"